name: Publish To Environment

on:
  workflow_dispatch:
    inputs:
      appVersion:
        description: App version to deploy (current, prerelease, draft, latest or version number)
        required: false
        default: 'current'
      environmentName:
        description: Environment to receive the new version (* for all)
        required: false
        default: '*'

defaults:
  run:
    shell: PowerShell

jobs:

  Environments:
    runs-on: windows-latest
    outputs:
      deployMatrix: ${{steps.Environments.outputs.deployMatrix}}
    steps:
      - name: Environments
        id: Environments
        run: |
          $environmentName = '${{github.event.inputs.environmentName}}'
          $headers = @{ 
            "Authorization" = "token ${{github.token}}"
            "Accept"        = "application/vnd.github.v3+json"
          }
          $url = "$($ENV:GITHUB_API_URL)/repos/$($ENV:GITHUB_REPOSITORY)/environments"
          $environments = Invoke-WebRequest -UseBasicParsing -Headers $headers -Uri $url | ConvertFrom-Json
          $deployMatrix = @{ "environment" = @($environments.environments.name | where-Object { $_.Split(' ')[0] -like $environmentName }) } | ConvertTo-Json -compress
          Write-Host "::set-output name=deployMatrix::$deployMatrix"
          Write-Host $deployMatrix
  Deploy:
    runs-on: windows-latest
    needs: [ Environments ]
    strategy:
      matrix: ${{fromJson(needs.Environments.outputs.deployMatrix)}}
      fail-fast: false
    name: Deploy to ${{matrix.environment}}
    environment:
      name: ${{matrix.environment}}
    steps:
      - name: Deploy
        uses: freddydk/myghgo/Deploy@main
        env:
          authContext: '${{secrets.AuthContext}}'
        with:
          environmentName: ${{matrix.environment}}
          artifactsUrl: ${{github.event.inputs.appVersion}}
