name: Publish To Environment

on:
  workflow_dispatch:
    inputs:
      appVersion:
        description: App version to deploy (current, prerelease, draft, latest or version number)
        required: false
        default: 'current'
      environmentName:
        description: Environment to receive the new version (* for all)
        required: false
        default: '*'

defaults:
  run:
    shell: PowerShell

jobs:

  Environments:
    runs-on: windows-latest
    outputs:
      deploymentMatrix: ${{steps.Environments.outputs.deploymentMatrix}}
      deploymentCount: ${{steps.Environments.outputs.deploymentCount}}
    steps:
      - name: Environments
        id: Environments
        run: |
          $environmentName = '${{github.event.inputs.environmentName}}'
          $headers = @{ 
            "Authorization" = "token ${{github.token}}"
            "Accept"        = "application/vnd.github.v3+json"
          }
          $url = "$($ENV:GITHUB_API_URL)/repos/$($ENV:GITHUB_REPOSITORY)/environments"
          $environments = Invoke-WebRequest -UseBasicParsing -Headers $headers -Uri $url | ConvertFrom-Json
          $useEnvironments = @($environments.environments | Where-Object { $_.Name -notlike '*(Production)*' -and $_.Name.Split(' ')[0] -like $environmentName } | ForEach-Object { $_.Name })
          $deploymentMatrix = @{ "environment" = $useEnvironments } | ConvertTo-Json -compress
          Write-Host "::set-output name=deploymentMatrix::$deploymentMatrix"
          Write-Host "::set-output name=deploymentCount::$($useEnvironments.Count)"
  Deploy:
    runs-on: windows-latest
    needs: [ Environments ]
    if: ${{needs.Environments.outputs.deploymentCount > 0}}
    strategy:
      matrix: ${{fromJson(needs.Environments.outputs.deploymentMatrix)}}
      fail-fast: false
    name: Deploy to ${{matrix.environment}}
    environment:
      name: ${{matrix.environment}}
    steps:
      - name: Deploy
        uses: freddydk/AL-Go-Actions/Deploy@main
        env:
          authContext: '${{secrets.AuthContext}}'
        with:
          environmentName: ${{matrix.environment}}
          artifactsUrl: ${{github.event.inputs.appVersion}}
          appSourceApp: 'Y'
