name: Update GitHub-Go System Files

on:
  workflow_dispatch:
    inputs:
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'

defaults:
  run:
    shell: PowerShell

jobs:
  update:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read settings
        uses: freddydk/myghgo/ReadSettings@main
        with:
          get: KeyVaultName,GhTokenWorkflowSecretName,TemplateUrl,TemplateBranch

      - name: Read secrets
        uses: freddydk/myghgo/ReadSecrets@main
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          keyVaultName: ${{ env.KEYVAULTNAME }}
          secrets: 'ghTokenWorkflow=${{ env.GHTOKENWORKFLOWSECRETNAME }}'

      - name: Update GitHub-Go system files
        uses: freddydk/myghgo/CheckForUpdates@main
        with:
          token: ${{ env.ghTokenWorkflow }}
          update: Y
          templateUrl: ${{ env.TemplateUrl }}
          branch: ${{ env.TemplateBranch }}
          directCommit: ${{ github.event.inputs.directCommit }}
